# Engine build identity: a digest of every engine source file and of the
# compiler configuration, compiled into lse_graph as engine_build_identity().
#
# The kernel JIT's launch index is keyed on it. That index lets a warm start
# make kernels resident without writing their source, so it must change
# whenever the source a kernel template would write could change -- and a
# template edit within one release changes no version number. Hashing the
# whole source tree (not a hand-kept list of "kernel files") is what makes
# that exact: a file missed by a list would serve another build's kernels.
#
# Two modes. Included from CMakeLists.txt, lse_add_build_identity(target)
# wires the generator. Run as a script (cmake -P) it does the hashing:
#   -DLSE_IDENTITY_LIST=<file listing sources, one per line>
#   -DLSE_IDENTITY_ROOT=<source root the listed paths are relative to>
#   -DLSE_IDENTITY_CONFIG=<compiler and build configuration text>
#   -DLSE_IDENTITY_OUT=<generated .cpp>
# The output is rewritten only when the digest changes, so an edit that
# leaves every byte in place recompiles nothing.

if(CMAKE_SCRIPT_MODE_FILE)
  file(STRINGS "${LSE_IDENTITY_LIST}" files)
  set(manifest "lse-build-identity-v1\n${LSE_IDENTITY_CONFIG}\n")
  foreach(rel IN LISTS files)
    file(SHA256 "${LSE_IDENTITY_ROOT}/${rel}" digest)
    string(APPEND manifest "${rel} ${digest}\n")
  endforeach()
  string(SHA256 identity "${manifest}")
  set(text "// Generated by cmake/LSEBuildIdentity.cmake; do not edit.\n#include <string_view>\n\nnamespace lse::graph {\nstd::string_view engine_build_identity() noexcept {\n  return \"${identity}\";\n}\n}  // namespace lse::graph\n")
  set(old "")
  if(EXISTS "${LSE_IDENTITY_OUT}")
    file(READ "${LSE_IDENTITY_OUT}" old)
  endif()
  if(NOT old STREQUAL text)
    file(WRITE "${LSE_IDENTITY_OUT}" "${text}")
  endif()
  return()
endif()

function(lse_add_build_identity target)
  set(root "${CMAKE_SOURCE_DIR}")
  file(GLOB_RECURSE sources CONFIGURE_DEPENDS RELATIVE "${root}"
       "${root}/src/*" "${root}/include/*")
  list(FILTER sources EXCLUDE REGEX "(^|/)\\.")
  list(SORT sources)
  set(list_file "${CMAKE_BINARY_DIR}/generated/lse_build_identity_sources.txt")
  string(REPLACE ";" "\n" listed "${sources}")
  file(CONFIGURE OUTPUT "${list_file}" CONTENT "${listed}\n")
  set(absolute "")
  foreach(rel IN LISTS sources)
    list(APPEND absolute "${root}/${rel}")
  endforeach()
  string(JOIN "|" config
    "${PROJECT_VERSION}" "${CMAKE_CXX_COMPILER_ID}" "${CMAKE_CXX_COMPILER_VERSION}"
    "${CMAKE_BUILD_TYPE}" "${CMAKE_CXX_FLAGS}" "${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}"
    "${CMAKE_SYSTEM_NAME}" "${CMAKE_SYSTEM_PROCESSOR}")
  set(out "${CMAKE_BINARY_DIR}/generated/lse_build_identity.cpp")
  set(stamp "${CMAKE_BINARY_DIR}/generated/lse_build_identity.stamp")
  add_custom_command(
    OUTPUT "${stamp}"
    BYPRODUCTS "${out}"
    COMMAND "${CMAKE_COMMAND}"
            "-DLSE_IDENTITY_LIST=${list_file}"
            "-DLSE_IDENTITY_ROOT=${root}"
            "-DLSE_IDENTITY_CONFIG=${config}"
            "-DLSE_IDENTITY_OUT=${out}"
            -P "${CMAKE_SOURCE_DIR}/cmake/LSEBuildIdentity.cmake"
    COMMAND "${CMAKE_COMMAND}" -E touch "${stamp}"
    DEPENDS ${absolute} "${list_file}" "${CMAKE_SOURCE_DIR}/cmake/LSEBuildIdentity.cmake"
    COMMENT "Hashing engine sources for the kernel launch index"
    VERBATIM)
  add_custom_target(${target}_build_identity DEPENDS "${stamp}")
  add_dependencies(${target} ${target}_build_identity)
  target_sources(${target} PRIVATE "${out}")
endfunction()
